name: Re-Release IPA As ZIP

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compress:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Existing Release IPA

        run: |

          mkdir ipa

          gh release download \
            --pattern "*.ipa" \
            --dir ipa

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Downloaded Files

        run: |

          ls -lh ipa

      - name: Compress IPA To ZIP

        run: |

          IPA_FILE=$(find ipa -name "*.ipa" | head -n 1)

          echo "IPA_FILE=$IPA_FILE"

          zip -r Recompressed-IPA.zip "$IPA_FILE"

          ls -lh Recompressed-IPA.zip

      - name: Upload ZIP Release

        uses: softprops/action-gh-release@v2

        with:

          tag_name: recompressed-${{ github.run_number }}

          name: Recompressed IPA ZIP

          files: |
            Recompressed-IPA.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
