name: Build And Release Unsigned IPA

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Schemes

        run: |

          PROJECT=$(find . -name "*.xcodeproj" | head -n 1)

          echo "PROJECT = $PROJECT"

          xcodebuild -list -project "$PROJECT"
